version: "3.9"

services:
  nextjs:
    build:
      context: .
    container_name: nextjs-app
    restart: always

  nginx:
    image: nginx:alpine
    container_name: nextjs-nginx
    ports:
      - "3000:80"   # Now available at http://localhost:3000
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - nextjs
